### ISSUE TITLE
Corrupt toprc on Ubuntu

### ISSUE THREAD

**Issue by Thhethssmuz** [Thhethssmuz/dotfiles#1]
`top` claims `.toprc` is corrupt on Ubuntu

I'm guessing this is a version issue were Ubuntu is using a significantly older version of top than Arch...

**Comment by clux** [comment]
Had this problem on debian:jessie as well. Decided to just provision everything with `htop` instead rather than having an almost unreadable toprc.

**Comment by Thhethssmuz** [comment]
Success, no longer have to deal with Ubuntu :D
